-- DATA-03: Create web_projects table for web design client project tracking
-- Each web design client (business with client_type = 'web_design' | 'both') can have
-- one or more web projects. Portal token enables public client access at /portal/[token].
--
-- RLS pattern: single-hop via business_id FK (same pattern as all other tenant tables).
-- Portal token lookup uses service-role client in the /portal/[token] Route Handler --
-- no anon SELECT policy needed here.

CREATE TABLE IF NOT EXISTS public.web_projects (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id               UUID NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,

  -- Project identity
  project_name              TEXT,
  domain                    TEXT,                 -- e.g. "plumbingpros.com"
  vercel_project_id         TEXT,                 -- optional Vercel reference
  status                    TEXT NOT NULL DEFAULT 'discovery'
    CHECK (status IN (
      'discovery', 'design', 'development', 'review', 'live', 'maintenance', 'paused', 'cancelled'
    )),

  -- Web design subscription (stored here, not on businesses -- avoids god-object pitfall)
  subscription_tier         TEXT
    CHECK (subscription_tier IN ('basic', 'advanced') OR subscription_tier IS NULL),
  subscription_started_at   DATE,
  subscription_monthly_fee  NUMERIC(10,2),        -- USD, e.g. 199.00 or 299.00
  has_review_addon          BOOLEAN NOT NULL DEFAULT false,

  -- Client contact (may differ from business owner)
  client_name               TEXT,
  client_email              TEXT,
  client_phone              TEXT,

  -- Project dates
  kickoff_date              DATE,
  target_launch_date        DATE,
  launched_at               TIMESTAMPTZ,          -- set when status moves to 'live'

  -- Portal access -- 192-bit base64url token (same generation pattern as form_token, intake_token)
  -- Generated via: randomBytes(24).toString('base64url')
  portal_token              TEXT,

  -- Page count (Basic: 1-4, Advanced: 4-10 per requirements)
  page_count                INTEGER,

  -- Internal notes (not visible to client)
  project_notes             TEXT,

  created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS
ALTER TABLE public.web_projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "web_projects_owner_all" ON public.web_projects
  USING (
    business_id IN (SELECT id FROM public.businesses WHERE user_id = auth.uid())
  )
  WITH CHECK (
    business_id IN (SELECT id FROM public.businesses WHERE user_id = auth.uid())
  );

-- Indexes
CREATE INDEX IF NOT EXISTS idx_web_projects_business_id
  ON public.web_projects(business_id);

-- Unique partial index for portal_token -- O(1) lookup without indexing NULLs
CREATE UNIQUE INDEX IF NOT EXISTS idx_web_projects_portal_token
  ON public.web_projects(portal_token)
  WHERE portal_token IS NOT NULL;

COMMENT ON TABLE public.web_projects IS
  'Web design projects for agency-managed businesses. One project per business is the initial model; schema supports multiple via the 1:many relationship.';
COMMENT ON COLUMN public.web_projects.portal_token IS
  '192-bit base64url token enabling unauthenticated client access at /portal/[token]. Generated via randomBytes(24).toString(base64url). Null until generated by agency.';
COMMENT ON COLUMN public.web_projects.subscription_tier IS
  'basic = $199/mo (1-4 pages, 2 revisions/mo), advanced = $299/mo (4-10 pages, 4 revisions/mo)';
